name: x64-windows-clang-cl

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  build-and-test:
    runs-on: windows-latest
    strategy:
      matrix:
        PRESET: [clang-win-debug, clang-win-release]
        WORK_ITEM: [CORO, FUNCORO]
    steps:
    - uses: actions/checkout@v4
      with:
        repository: tzcnt/tmc-examples
        ref: main
    - name: branch-examples
      continue-on-error: true
      run: git checkout ${{env.BRANCH_NAME}}
    - name: submodule-clone
      run: >
        cd submodules
        && git clone https://github.com/tzcnt/TooManyCooks.git
        && git clone https://github.com/tzcnt/tmc-asio.git
    # If a branch with the same name exists in the dependency repos, use that. Otherwise, use main.
    - name: submodule-branch-TMC
      # continue-on-error: true # this should never fail if triggered from TMC workflow
      run: cd submodules/TooManyCooks && git checkout ${{env.BRANCH_NAME}}
    - name: submodule-branch-tmc-asio
      continue-on-error: true
      run: cd submodules/tmc-asio && git checkout ${{env.BRANCH_NAME}}
    - uses: ilammy/msvc-dev-cmd@v1
    - name: configure
      run: cmake -G "Ninja" -DTMC_AS_SUBMODULE=ON -DCMD_FLAGS='-DTMC_WORK_ITEM=${{matrix.WORK_ITEM}}' --preset ${{matrix.PRESET}} .
    - name: build
      run: cmake --build ./build/${{matrix.PRESET}} --target all
    - name: run tests
      run: ./build/${{matrix.PRESET}}/tests/tests.exe
