name: ThreadSanitizer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        PRESET: [clang-linux-debug]
        WORK_ITEM: [CORO]
    steps:
    - uses: actions/checkout@v4
      with:
        repository: tzcnt/tmc-examples
        ref: main
    - name: branch-examples
      continue-on-error: true
      run: git fetch && git checkout ${{env.BRANCH_NAME}}
    - name: submodule-clone
      run: >
        cd submodules
        && git clone https://github.com/tzcnt/TooManyCooks.git
        && git clone https://github.com/tzcnt/tmc-asio.git
    # If a branch with the same name exists in the dependency repos, use that. Otherwise, use main.
    - name: submodule-branch-TMC
      # continue-on-error: true # this should never fail if triggered from TMC workflow
      run: cd submodules/TooManyCooks && git fetch && git checkout ${{env.BRANCH_NAME}}
    - name: submodule-branch-tmc-asio
      continue-on-error: true
      run: cd submodules/tmc-asio && git fetch && git checkout ${{env.BRANCH_NAME}}
    - name: configure
      run: cmake -G "Unix Makefiles" -DTMC_AS_SUBMODULE=ON -DCMD_COMPILE_FLAGS='-DTMC_WORK_ITEM=${{matrix.WORK_ITEM}};-fsanitize=thread' -DCMD_LINK_FLAGS='-fsanitize=thread' --preset ${{matrix.PRESET}} .
    - name: build
      run: cmake --build ./build/${{matrix.PRESET}} --parallel $(nproc) --target all
    - name: run tests
      run: TSAN_OPTIONS="halt_on_error=1" ./build/${{matrix.PRESET}}/tests/tests
